### ISSUE TITLE
Use TOML for our configuration files

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Phosphor#10]
TOML would be the perfect solution for our needs in place of JSON, and would only require the rather small addition of the [Toml4J library](https://github.com/mwanji/toml4j), which weighs in at ~70KB.

**Comment by jellysquid3** [comment]
Frankly, this would be largely overkill given our configuration files never grew to a size that would justify adding in a 70KB library.

**Comment by Devan-Kerman** [comment]
You could use java properties, they are pretty good and you don't need to add anything
