### ISSUE TITLE
[Phosphor 0.2.3] - Client doesn't load mods (conflict Make-zoom-zoom mod)

### ISSUE THREAD

**Issue by Finelarme9** [jellysquid3/Phosphor#11]
Hey there
- **Infos** : Forge 2830 / Version 1.12 / Clean version / 2 mods tested.
- **Bug/how to reproduce** : When we use the last version https://minecraft.curseforge.com/projects/make-zoom-zoom/files/2588781 + https://minecraft.curseforge.com/projects/phosphor/files/2706848 the client refuse to load the 2 mods (it closes with an error message/no crashlog). Picture https://i.imgur.com/lAmwNfn.jpg .
[debug.log](https://github.com/jellysquid3/Phosphor/files/3143860/debug.log)
[latest.log](https://github.com/jellysquid3/Phosphor/files/3143861/latest.log)
Do you have an idea ? Thank you for your work. I love your stuff.
Ben

**Comment by jellysquid3** [comment]
"Make Zoom Zoom" is shipping an old version of Sponge Mixins, which prevents Phosphor from working correctly. The mod's author should update from version `0.7.8` to `0.7.10` (released June of 2018), which is the earliest version Phosphor will accept.

**Comment by jellysquid3** [comment]
This may be resolved in the future by moving away from using Sponge Mixins. See #12 for more information.
