### ISSUE TITLE
Move away from using Sponge Mixins

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Phosphor#12]
Sponge Mixins have been more pain than they are worth in my experience. We currently have to implement many awful injections and redirects to get around Mixin's imposed restrictions and shade in a large dependency. The documentation for the project is lacking, support is limited to a few oracle individuals, and classpath conflicts with other mods (see #11) are common. Additionally, it is uncertain whether or not Sponge Mixins will ever be available for Forge on 1.13+ and are currently a blocker for updating to newer versions.

There are also additional sources of overhead caused by Mixins allocating callback information objects in some hot methods and various limitations that prevent us from ensuring all our ASM transformations have applied successfully.

We should switch to writing our own (minimal and small) ASM framework to replace Sponge Mixins, improve compatibility and performance of the mod, and allow ourselves to update to newer versions.

**Comment by jellysquid3** [comment]
Status update for the folks playing along at home. Progress is coming along nicely for the annotation-based transformer library I've been working on to replace Sponge Mixins. I hope to publish the library's source code to GitHub soon and publish the `next-0.3` branch next week.

**Comment by Darkhax** [comment]
Hello, sorry for bothering you. It's been a while since you've posted to GitHub and I am curious to know if you are still planning to work on the custom framework. It sounds very interesting based on what you've shared publicly so far.

**Comment by jellysquid3** [comment]
@Darkhax Hello there! It's no bother. I've been a pretty aloof lately due to trying to find work and the likes and have not had time until recently to work on Phosphor or my class transformation framework again. I'm still very much planning on completing work on my framework as Mixins appears dead in the water for Minecraft 1.14 (and I have many more performance-related patches I'd like to publish in the future...)

Hopefully you should see a GitHub repository pop up soon alongside a branch demonstrating it in action for Phosphor. I don't anticipate it taking too much longer to get into a practical state.

**Comment by Darkhax** [comment]
That's great to hear, thank you for the update. I look forward to checking things out when you're ready to post them ^^

**Comment by jellysquid3** [comment]
There's not been an update for a while on this issue, so I figure now is the time to write up a little about what's going on.

The fate of Sponge's Mixins has changed in the past few months. In particular, we're now seeing support for Sponge Mixins in Forge for Minecraft 1.14, which was the largest of concerns here. My own work on [Stitcher](https://github.com/jellysquid3/stitcher), which was my own attempt at a bytecode transformation library similar to the likes of Mixins, was a good learning exercise, but ultimately matching the genius that is Mixins simply is not in my wheelhouse. 

Given this turn of events, my plans moving forward are to continue using Mixins. I hope with continued adoption by Forge, it will soon receive first-class support and resolve the issue of bootstrapping.
