### ISSUE TITLE
Incompatibility with the Skygrid mod: Game freezes when creating worlds

### ISSUE THREAD

**Issue by Dimentive** [jellysquid3/Phosphor#13]
If Phosphor is installed alongside [Skygrid](https://minecraft.curseforge.com/projects/skygrid), a mod that changes the default worldgen to generate worlds with blocks in a “grid” (inspired by SethBling’s seven-year-old [SkyGrid survival map](https://www.youtube.com/watch?v=5dhs3ithXDA)), the game will get forever stuck on “Building terrain”—or just a background with no text—when creating a world (however, worlds can be entered just fine; just not created).

This was tested in an instance with only Skygrid and Phosphor installed—no other mods. I’m not sure whether this is an issue on Skygrid’s side or on Phosphor’s side. I assume it’s on Skygrid’s side, but I’m creating an issue here just in case it isn’t. Plus, you might know what could be causing this; the developer of Skygrid doesn’t seem to know, so any insight would surely be useful in fixing this problem.

**Log:** https://pastebin.com/raw/tKAAzQyD

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Skygrid:** [1.3.1](https://minecraft.curseforge.com/projects/skygrid/files/2702633) (latest)
* **Phosphor:** [0.2.2](https://minecraft.curseforge.com/projects/phosphor/files/2698698) (latest)

**Comment by jellysquid3** [comment]
[This is fixed with release 0.2.4.](https://minecraft.curseforge.com/projects/phosphor/files/2707000)

**Comment by Dimentive** [comment]
Awesome! Thanks!

**Comment by Dimentive** [comment]
Awesome! Thank you!

**Comment by PssbleTrngle** [comment]
What exactly was the issue causing it?
Did I do something wrong at the generation with my mod?

**Comment by jellysquid3** [comment]
@PssbleTrngle There was a bug in Phosphor that led to re-entrance in the lighting engine when the void is exposed to the world. Because of the lock we used, re-entrance would cause a deadlock, freezing the game.
