### ISSUE TITLE
Crash with 0.2.4

### ISSUE THREAD

**Issue by chunkedelement** [jellysquid3/Phosphor#15]
Forge 14.23.5.2836
phosphor-1.12.2-0.2.4+build46-universal
version 0.2.2 works fine on both client and server. When updating to version 0.2.4 on client and server I consistently get the following error upon loading.
https://pastebin.com/aZdZtaf7
Same with twitch:
[latest.log](https://github.com/jellysquid3/Phosphor/files/3145819/latest.log)
Downgrade to version 0.2.2 all is fine
Just read though this, on 0.2.3- is there another mod that is causing the mixin issue to crash
- Marked Phosphor's mixins as "required" so failures to load them results in the game crashing rather than the mod being silently disabled
Thanks

**Comment by jellysquid3** [comment]
There is another mod providing an old version of Mixins, which prevents Phosphor from even initializing. If you are now suddenly crashing, this means that Phosphor previously did not work at all in 0.2.2 and only silently failed instead.  You will need to remove mods one by one (or use a utility to find which mods contain the `org.spongepowered` package) and either remove the mod or update it to a newer version which will hopefully provide an updated version of Mixins.

This is one of the many issues of us using Sponge Mixins and I am to have it resolved in the 0.3.0 release with #12, but for the time being there is nothing I can do to fix it.

**Comment by chunkedelement** [comment]
ok thanks for feedback
