### ISSUE TITLE
Notifying about incompatibility with OpenCubicChunks

### ISSUE THREAD

**Issue by juh9870** [jellysquid3/Phosphor#26]
Phosphor is incompatible with OpenCubicChunks because [it uses its own lighting propagation  system](https://github.com/OpenCubicChunks/CubicChunks/issues/436#issuecomment-478331294), I think its worth listing in incompatibility list.

**Comment by jellysquid3** [comment]
Thanks for the notice! I've added it to the (in)compatibility list with the following snippet.

> **OpenCubicChunks compatibility**
> Due to the fact that OpenCubicChunks implements its own light propagation system, Phosphor is unfortunately fundamentally incompatible with this mod.

**Comment by Barteks2x** [comment]
Note that in theory it should be possible to make cubic chunks *load* with phosphor and for phosphor to work as intended for non-cubicchunks dimensions and worlds. But as it is the Chunk class patches are conflicting and I would have to look into how to get around it.

**Comment by border999** [comment]
I would love to see this compatibility issue fixed. @jellysquid3 @Barteks2x

**Comment by Barteks2x** [comment]
Again, this is not going to work in any useful way. It may be possible to have it not crash. Beyond that, CC needs to have builtin optimized light propagation code.

**Comment by border999** [comment]
@Barteks2x if you can tell me with any degree of certainty that your lighting code is comparable to Phosphor across the various dimensions in terms of performance, I will pull Phosphor out of my pack and never look back.

**Comment by Barteks2x** [comment]
It's not **yet**. But that's not the point. The point is, cubic chunks is replacing the light propagation system on it's own. Making phosphor run with it would serve no purpose, the right way to do it is to fix the light propagation system in cubic chunks.
