### ISSUE TITLE
Optifine

### ISSUE THREAD

**Issue by Dave811** [jellysquid3/Phosphor#28]
I dont know if phosphor is the problem, but I play the modpack Omnifactory on the Version 1.1.0
and I installed phosphor and optifine by hand. On Version 1.0.6 both mods work together.
Now If I install both the game would not start.
After I removed Phosphor the game launched.
Here is the log: https://pastebin.com/QG2UM3CH
And here the other log from the other file: https://pastebin.com/RhvhGjFg

**Comment by jellysquid3** [comment]
This is caused by p455w0rd's Library. Please update to the latest version (1.12.2-2.2.150, released ten hours ago as of the time of writing)  of p455w0rd's Library to fix the issue. For more information, see #27.
