### ISSUE TITLE
[Phosphor 0.2.4]The game windows didn't come up when this mod is added

### ISSUE THREAD

**Issue by chinesexs** [jellysquid3/Phosphor#29]
Sorry for the Chinese words below,hopefully it doesn't make you folks have a bad day =(
> [00:43:51] [main/INFO]: Loading tweak class name 
> 
> net.minecraftforge.fml.common.launcher.FMLTweaker
> [00:43:51] [main/INFO]: Using primary tweak class name 
> 
> net.minecraftforge.fml.common.launcher.FMLTweaker
> [00:43:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
> [00:43:51] [main/INFO]: Forge Mod Loader version 14.23.5.2768 for Minecraft 1.12.2 loading
> [00:43:51] [main/INFO]: Java is Eclipse OpenJ9 VM, version 1.8.0_202, running on Windows 
> 
> 7:amd64:6.1, installed at C:\Program Files\AdoptOpenJDK\jdk-8.0.202.08\jre
> [00:43:51] [main/INFO]: Searching D:\小实的文件夹\游戏目录\mc\小实的单人生存\.minecraft\mods for 
> 
> mods
> [00:43:51] [main/INFO]: Searching D:\小实的文件夹\游戏目录\mc\小实的单人生存\.minecraft\mods
> 
> \1.12.2 for mods
> [00:43:51] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in [R键整理]InventoryTweaks-
> 
> 1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [00:43:52] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion 
> 
> annotation, it may cause issues with this version of Minecraft
> [00:43:52] [main/WARN]: The coremod me.towdium.jecharacters.core.JechCore does not have a 
> 
> MCVersion annotation, it may cause issues with this version of Minecraft
> [00:43:52] [main/WARN]: The coremod JechCore (me.towdium.jecharacters.core.JechCore) is not 
> 
> signed!
> [00:43:52] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in [平滑字体]SmoothFont-
> 
> mc1.12.2-2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [00:43:52] [main/WARN]: The coremod bre.smoothfont.asm.CorePlugin does not have a MCVersion 
> 
> annotation, it may cause issues with this version of Minecraft
> [00:43:52] [main/WARN]: The coremod CorePlugin (bre.smoothfont.asm.CorePlugin) is not signed!
> [00:43:52] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from [更
> 
> 好的FPS] BetterFps-1.4.8.jar
> [00:43:52] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from [更快的
> 
> 加载]MakeZoomZoom-0.0.4.jar
> [00:43:52] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from [高清修复]preview-
> 
> OptiFine_1.12.2_HD_U_E4_pre4.jar
> [00:43:52] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in [泡沫修复]foamfix-0.10.5-
> 
> 1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [00:43:52] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a 
> 
> MCVersion annotation, it may cause issues with this version of Minecraft
> [00:43:52] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in [连接材质]CTM-MC1.12.2-
> 
> 0.3.3.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [00:43:52] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a 
> 
> MCVersion annotation, it may cause issues with this version of Minecraft
> [00:43:52] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) 
> 
> is not signed!
> [00:43:52] [main/WARN]: The coremod com.therandomlabs.randompatches.core.RPCore does not have 
> 
> a MCVersion annotation, it may cause issues with this version of Minecraft
> [00:43:52] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AdvancedRocketry-1.12.2-
> 
> 1.5.0-139-universal.jar. This is not recommended, @Mods should be in a separate jar from the 
> 
> coremod.
> [00:43:52] [main/WARN]: The coremod AdvancedRocketryPlugin 
> 
> (zmaster587.advancedRocketry.asm.AdvancedRocketryPlugin) is not signed!
> [00:43:52] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Aroma1997Core-1.12.2-
> 
> 2.0.0.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [00:43:52] [main/WARN]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion 
> 
> annotation, it may cause issues with this version of Minecraft
> [00:43:52] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in HammerCore-1.12.2-
> 
> 2.0.4.7.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [00:43:52] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Mekanism-1.12.2-
> 
> 9.7.8.379.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [00:43:52] [main/WARN]: The coremod mekanism.coremod.MekanismCoremod does not have a MCVersion 
> 
> annotation, it may cause issues with this version of Minecraft
> [00:43:52] [main/WARN]: The coremod MekanismCoremod (mekanism.coremod.MekanismCoremod) is not 
> 
> signed!
> [00:43:52] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in p455w0rdslib-1.12.2-
> 
> 2.2.151.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
> [00:43:52] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from [光照引
> 
> 擎]phosphor-1.12.2-0.2.4+build46-universal.jar
> [00:43:52] [main/WARN]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin 
> 
> does not have a MCVersion annotation, it may cause issues with this version of Minecraft
> [00:43:52] [main/INFO]: Loading tweak class name 
> 
> net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
> [00:43:52] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
> [00:43:52] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
> [00:43:52] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.8 Source=file:/D:/小实的文件
> 
> 夹/游戏目录/mc/小实的单人生存/.minecraft/mods/%5B更快的加载%5DMakeZoomZoom-0.0.4.jar 
> 
> Service=LaunchWrapper Env=CLIENT
> [00:43:52] [main/DEBUG]: Instantiating coremod class MZZLoadingPlugin
> [00:43:52] [main/DEBUG]: The coremod xyz.ajp.makezoomzoom.asm.MZZLoadingPlugin requested 
> 
> minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
> [00:43:52] [main/DEBUG]: Found signing certificates for coremod MZZLoadingPlugin 
> 
> (xyz.ajp.makezoomzoom.asm.MZZLoadingPlugin)
> [00:43:52] [main/DEBUG]: Found certificate 0a35e4a98424a7588a4bd9a32c3088ecb6607b2a
> [00:43:52] [main/DEBUG]: Enqueued coremod MZZLoadingPlugin
> [00:43:52] [main/DEBUG]: Instantiating coremod class PhosphorFMLLoadingPlugin
> [00:43:52] [main/DEBUG]: The coremod me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin 
> 
> requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
> [00:43:52] [main/DEBUG]: Found signing certificates for coremod PhosphorFMLLoadingPlugin 
> 
> (me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin)
> [00:43:52] [main/DEBUG]: Found certificate f0387d288626cc2d937daa504e74af570c52a2f1
> [00:43:52] [main/DEBUG]: Enqueued coremod PhosphorFMLLoadingPlugin
> [00:43:52] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
> [00:43:52] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already 
> 
> been visited -- skipping
> [00:43:52] [main/INFO]: Loading tweak class name 
> 
> net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
> [00:43:52] [main/INFO]: Calling tweak class 
> 
> net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
> [00:43:52] [main/INFO]: Calling tweak class 
> 
> net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
> [00:43:52] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
> [00:43:52] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: 
> 
> acceptOptions
> [00:43:52] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: 
> 
> injectIntoClassLoader
> [00:43:52] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
> [00:43:52] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: D:\小
> 
> 实的文件夹\游戏目录\mc\小实的单人生存\.minecraft\mods\[高清修复]preview-
> 
> OptiFine_1.12.2_HD_U_E4_pre4.jar
> [00:43:52] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager
> 
> $FMLPluginWrapper
> [00:43:52] [main/DEBUG]: Injecting coremod FMLCorePlugin 
> 
> \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
> [00:43:52] [main/TRACE]: Registering transformer 
> 
> net.minecraftforge.fml.common.asm.transformers.SideTransformer
> [00:43:52] [main/TRACE]: Registering transformer 
> 
> net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
> [00:43:52] [main/TRACE]: Registering transformer 
> 
> net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
> [00:43:52] [main/TRACE]: Registering transformer 
> 
> net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
> [00:43:52] [main/DEBUG]: Injection complete
> [00:43:52] [main/DEBUG]: Running coremod plugin for FMLCorePlugin 
> 
> \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
> [00:43:52] [main/DEBUG]: Running coremod plugin FMLCorePlugin
> [00:43:55] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint 
> 
> e3c3d50c7c986df74c645c0ac54639741c90a557
> [00:43:55] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint 
> 
> cd99959656f753dc28d863b46769f7f8fbaefcfc
> [00:43:55] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
> [00:43:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager
> 
> $FMLPluginWrapper
> [00:43:55] [main/DEBUG]: Injecting coremod FMLForgePlugin 
> 
> \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
> [00:43:55] [main/DEBUG]: Injection complete
> [00:43:55] [main/DEBUG]: Running coremod plugin for FMLForgePlugin 
> 
> \{net.minecraftforge.classloading.FMLForgePlugin\}
> [00:43:55] [main/DEBUG]: Running coremod plugin FMLForgePlugin
> [00:43:55] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
> [00:43:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager
> 
> $FMLPluginWrapper
> [00:43:55] [main/DEBUG]: Injecting coremod JechCore \{me.towdium.jecharacters.core.JechCore\} 
> 
> class transformers
> [00:43:55] [main/TRACE]: Registering transformer 
> 
> me.towdium.jecharacters.core.JechClassTransformer
> [00:43:55] [main/DEBUG]: Injection complete
> [00:43:55] [main/DEBUG]: Running coremod plugin for JechCore 
> 
> \{me.towdium.jecharacters.core.JechCore\}
> [00:43:55] [main/DEBUG]: Running coremod plugin JechCore
> [00:43:56] [main/INFO]: Starting generating pattern
> [00:43:56] [main/INFO]: Starting loading pinyin data
> [00:43:56] [main/INFO]: Finished loading pinyin data
> [00:43:56] [main/INFO]: Finished generating pattern
> [00:43:56] [main/DEBUG]: Coremod plugin class JechCore run successfully
> [00:43:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager
> 
> $FMLPluginWrapper
> [00:43:56] [main/DEBUG]: Injecting coremod CorePlugin \{bre.smoothfont.asm.CorePlugin\} class 
> 
> transformers
> [00:43:56] [main/TRACE]: Registering transformer bre.smoothfont.asm.Transformer
> [00:43:56] [main/DEBUG]: Injection complete
> [00:43:56] [main/DEBUG]: Running coremod plugin for CorePlugin 
> 
> \{bre.smoothfont.asm.CorePlugin\}
> [00:43:56] [main/DEBUG]: Running coremod plugin CorePlugin
> [00:43:56] [main/INFO]: OptiFine was detected.
> [00:43:56] [main/DEBUG]: Coremod plugin class CorePlugin run successfully
> [00:43:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager
> 
> $FMLPluginWrapper
> [00:43:56] [main/DEBUG]: Injecting coremod AdvancedRocketryPlugin 
> 
> \{zmaster587.advancedRocketry.asm.AdvancedRocketryPlugin\} class transformers
> [00:43:56] [main/TRACE]: Registering transformer 
> 
> zmaster587.advancedRocketry.asm.ClassTransformer
> [00:43:56] [main/DEBUG]: Injection complete
> [00:43:56] [main/DEBUG]: Running coremod plugin for AdvancedRocketryPlugin 
> 
> \{zmaster587.advancedRocketry.asm.AdvancedRocketryPlugin\}
> [00:43:56] [main/DEBUG]: Running coremod plugin AdvancedRocketryPlugin
> [00:43:56] [main/DEBUG]: Coremod plugin class AdvancedRocketryPlugin run successfully
> [00:43:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager
> 
> $FMLPluginWrapper
> [00:43:56] [main/DEBUG]: Injecting coremod CoreMod \{aroma1997.core.coremod.CoreMod\} class 
> 
> transformers
> [00:43:56] [main/DEBUG]: Injection complete
> [00:43:56] [main/DEBUG]: Running coremod plugin for CoreMod \{aroma1997.core.coremod.CoreMod\}
> [00:43:56] [main/DEBUG]: Running coremod plugin CoreMod
> [00:43:56] [main/INFO]: Finished data injection.
> [00:43:56] [main/INFO]: Finished data injection.
> [00:43:56] [main/DEBUG]: Coremod plugin class CoreMod run successfully
> [00:43:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager
> 
> $FMLPluginWrapper
> [00:43:56] [main/DEBUG]: Injecting coremod HCASM \{com.zeitheron.hammercore.asm.HCASM\} class 
> 
> transformers
> [00:43:56] [main/TRACE]: Registering transformer 
> 
> com.zeitheron.hammercore.asm.HammerCoreTransformer
> [00:43:56] [main/DEBUG]: Injection complete
> [00:43:56] [main/DEBUG]: Running coremod plugin for HCASM 
> 
> \{com.zeitheron.hammercore.asm.HCASM\}
> [00:43:56] [main/DEBUG]: Running coremod plugin HCASM
> [00:43:56] [main/DEBUG]: Coremod plugin class HCASM run successfully
> [00:43:56] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
> [00:43:56] [main/INFO]: Initialised Mixin FML Remapper Adapter with 
> 
> net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@ba161d49
> [00:43:56] [main/DEBUG]: Injecting coremod MZZLoadingPlugin 
> 
> \{xyz.ajp.makezoomzoom.asm.MZZLoadingPlugin\} class transformers
> [00:43:56] [main/INFO]: Compatibility level set to JAVA_8
> [00:43:56] [main/TRACE]: Registering transformer xyz.ajp.makezoomzoom.asm.MZZClassTransformer
> [00:43:56] [main/DEBUG]: Injection complete
> [00:43:56] [main/DEBUG]: Running coremod plugin for MZZLoadingPlugin 
> 
> \{xyz.ajp.makezoomzoom.asm.MZZLoadingPlugin\}
> [00:43:56] [main/DEBUG]: Running coremod plugin MZZLoadingPlugin
> [00:43:56] [main/DEBUG]: Coremod plugin class MZZLoadingPlugin run successfully
> [00:43:56] [main/DEBUG]: Injecting coremod PhosphorFMLLoadingPlugin 
> 
> \{me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin\} class transformers
> [00:43:56] [main/DEBUG]: Injection complete
> [00:43:56] [main/DEBUG]: Running coremod plugin for PhosphorFMLLoadingPlugin 
> 
> \{me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin\}
> [00:43:56] [main/DEBUG]: Running coremod plugin PhosphorFMLLoadingPlugin
> [00:43:56] [main/INFO]: Phosphor has been hooked by Forge, setting up Mixin and plugins
> [00:43:56] [main/WARN]: Mixin config mixins.phosphor.json requires mixin subsystem version 
> 
> 0.7.10 but 0.7.8 was found. The mixin config will not be applied.
> Exception in thread "main" org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.phosphor.json requires mixin subsystem version 0.7.10
>         at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)
>         at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
>         at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
>         at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
>         at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)
>         at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)
>         at me.jellysquid.mods.phosphor.core.PhosphorFMLSetupHook.call(PhosphorFMLSetupHook.java:24)
>         at me.jellysquid.mods.phosphor.core.PhosphorFMLSetupHook.call(PhosphorFMLSetupHook.java:11)
>         at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:164)
>         at org.spongepowered.asm.launch.platform.MixinPlatformAgentFML.inject(MixinPlatformAgentFML.java:317)
>         at org.spongepowered.asm.launch.platform.MixinContainer.inject(MixinContainer.java:124)
>         at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:203)
>         at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:189)
>         at org.spongepowered.asm.launch.MixinTweaker.injectIntoClassLoader(MixinTweaker.java:62)
>         at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
As the log file shows,the game wasn't unable to launch but similar to that

**Comment by jellysquid3** [comment]
MakeZoomZoom is providing an old version of Sponge Mixins. Users have reported this before, but to the best of my knowledge it has not been fixed yet by MakeZoomZoom. You will have to remove MakeZoomZoom or Phosphor in order to play.
