### ISSUE TITLE
Server tick rate grinds to a halt

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Phosphor#3]
[Originally opened by **Goshen** on the Gitea repository.](https://gitea.gildedgames.com/jellysquid/Phosphor/issues/16)

> https://i.gyazo.com/6c758f85044938ec906a4a5732b21059.png
>
> Warmroast html attached.
>
> I had a player that whenever he would log in would drop the server from 20 tps to .5, removed phosphor and aether and he is now logged in with 20 tps.
>
> phosphor-1.12.2-0.1.7.1+build35-universal.jar
> aether_ii-1.12.2-0.2.0+build42-universal.jar
>
> Modpack - https://minecraft.curseforge.com/projects/drtardis-2-new-adventures

**Comment by jellysquid3** [comment]
@ProsperCraft Does this issue still occur with the latest version of Phosphor?

**Comment by DatrixTHLK** [comment]
Hi, 

I can say yes it still does. https://gist.github.com/DatrixTHLK/86a536bf71c95d64f70efd5753235294 Massive console spam in the FML Log. This is only a small portion of the fml log.

Minecraft 1.12.2
Forge: 14.23.5.2836
Phosphor: 0.2.2

**Comment by jellysquid3** [comment]
@DatrixTHLK The problem you are experiencing is unrelated to this issue (which is not caused by Phosphor imposing thread locks), and is instead a result of the mod Fire and Ice spawning particles on the client with an instance of the server's world. This is bad practice and a violation of vanilla's contract. As a consequence of this bad behavior on part of their mod, Phosphor is protecting the game from crashing by locking the client and server threads to restore the game to a safe state, which introduces the lag spikes you are experiencing. In vanilla, this would result in unstable behavior, corrupted world state, or crashes.

There is unfortunately nothing I can do to resolve the issue, and it is the responsibility of the Ice and Fire mod's authors to patch the issue.

More details can be found in the now archived issue found [here](https://gitea.gildedgames.com/jellysquid/Phosphor/issues/23).

**Comment by DatrixTHLK** [comment]
Alright, will do, I will send the issue to fire and ice.

**Comment by jellysquid3** [comment]
I'm going to close this issue as I've not been able to get in contact with the author of the original issue and it's not clear where/if Phosphor is at fault here. If anyone is able to reproduce this specific issue (being that `IWorldEventListener#notifyLightSet(BlockPos)` takes almost all of the server's tick time), please re-open this issue with additional information.
