### ISSUE TITLE
Crash on startup with MovingWorld

### ISSUE THREAD

**Issue by CammiePone** [jellysquid3/Phosphor#31]
Phosphor's mixin doesn't apply when MovingWorld is installed, leading to a crash on startup. No crash report is generated, just a log.
https://pastebin.com/mmLUGmAS

**Comment by jellysquid3** [comment]
> SpongePowered MIXIN Subsystem Version=0.7.4 Source=file:/C:/Users/Lily/Documents/Curse/Minecraft/Instances/Bewitchment/mods/movingworld-1.12-6.342-full.jar Service=LaunchWrapper Env=CLIENT
> Mixin config mixins.phosphor.json requires mixin subsystem version 0.7.10 but 0.7.4 was found. The mixin config will not be applied.

MovingWorld provides a very old version of Sponge Mixins. There is nothing we can do about this issue. Please ask the developers of MovingWorld to update to the newest version of Mixins.

**Comment by CammiePone** [comment]
Yeah, had a feeling it was an issue they'd have to fix. Unfortunately, the mod's 1.12 branch has been dead in the water for almost 2 years.
