### ISSUE TITLE
Memory Leak with Spongforge?

### ISSUE THREAD

**Issue by TheRealDadbeard** [jellysquid3/Phosphor#32]
spongeforge-1.12.2-2838-7.1.7-RC3819

RAM usage went way above 11GB and after removing this mod it tops out at 8GB which is normal for a heap size of 6GB. I looked in VisualVM but could not find anything related and it would crash after like 10s sadly.

**Comment by jellysquid3** [comment]
Have you disabled Sponge's async lighting patch?

**Comment by TheRealDadbeard** [comment]
Will do. I'm monitoring with visualvm and will test some things then report back as I need to be sure what is causing this as I have over 100mods

**Comment by TheRealDadbeard** [comment]
seems to not be your mod, still looking for the culprit
