### ISSUE TITLE
Incompatibility with Ice and Fire Mod

### ISSUE THREAD

**Issue by Secretname2009** [jellysquid3/Phosphor#33]
Ive checked the Closed Issues there for Ice and Fire but the issue there didnt match this problem.

It randomly happends when pixies are in loaded chunks. There isnt much detail i can provide due to it happening while using the F3 Debug Pie menu
The entire screen goes light blue and VanillaFix appears saying Phosphor and Ice and Fire are the causes for this crash.
Minecraft 1.12.2
Phosphor 0.2.4
Forge 14.23.5.2838
[crash-2019-07-08_22.07.11-client.txt](https://github.com/jellysquid3/Phosphor/files/3370068/crash-2019-07-08_22.07.11-client.txt)

**Comment by jellysquid3** [comment]
This is an issue on Ice and Fire's side with many open issues already present (see PR https://github.com/Alex-the-666/Ice_and_Fire/pull/1569 for the list of issues).

That said, this broken behaviour on their part is supposed to be caught by a trap in Phosphor before lighting updates begin being processed, allowing the game to at least continue running (although with poorer performance). As such, this issue will track this problem instead.
