### ISSUE TITLE
Incompatibility with hybrid servers.

### ISSUE THREAD

**Issue by Zilacon** [jellysquid3/Phosphor#35]
https://github.com/PFCraft/Mohist/issues/120

Can this be resolved?

**Comment by jellysquid3** [comment]
I'm not interested in providing support for "hybrid" servers. These kind of projects have popped up dozens of times under a different name (MCPC, Cauldron, KCauldron, Thermos, Contigo, Kettle, now Mohist) all with the same issues. It's an absolute headache to provide support for and above my pay grade. Server administrators and plugin authors should consider upgrading from Bukkit-era plugins at this point.

Furthermore, the linked issue includes multiple conflicts and warnings. I've not seen an incompatibility with TickDynamic before... as such, I'm suspecting an issue with Mohist. If there is in fact an issue with the mod that is not reproducible with Mohist, please file a new issue and include a full server debug log with it.

All that said, it seems Mohist includes an async lighting patch (no idea what from, it could be Paper, whatever part it's cannibalized) which is fundamentally incompatible with Phosphor. Hopefully they've kept the configuration option to disable this... If you can find it and disable the async patch, it may help you run Phosphor.

**Comment by Mgazul** [comment]
Already fixed in Mohist
