### ISSUE TITLE
Multiple Minecraft version support?

### ISSUE THREAD

**Issue by killzoms** [jellysquid3/Phosphor#37]
Will additional(previous) versions of Minecraft be supported sometime in the future? I understand that working backwards is harder than working forwards.

**Comment by jellysquid3** [comment]
For the time being, there are no plans to port Phosphor to older versions of Minecraft. If there shows to be considerable demand for those versions of the game, it may be considered.

That said, this issue tracker is primarily intended for reporting issues such as bugs, crashes, and other problems. These kinds of questions are better suited for the Curseforge page or Discord server.
