### ISSUE TITLE
Crash Entering Nether on 0.2.1

### ISSUE THREAD

**Issue by TwilightPSN** [jellysquid3/Phosphor#4]
[crash-2019-04-13_12.48.43-server.txt](https://github.com/jellysquid3/Phosphor/files/3076472/crash-2019-04-13_12.48.43-server.txt)

Went to enter the nether and had it crash. Downgraded and was able to enter just fine

**Comment by jellysquid3** [comment]
Derp. We're not checking if the dimension uses sky light or not. Expect a new release with the fix very soon.

**Comment by TwilightPSN** [comment]
glad i could help :)

**Comment by jellysquid3** [comment]
This issue has been resolved in 0.2.2, which is [now available on Curseforge](https://minecraft.curseforge.com/projects/phosphor/files/2698698). Thank you for the report.
