### ISSUE TITLE
Phosphor, currently incompatible with Cubic Chunks

### ISSUE THREAD

**Issue by border999** [jellysquid3/Phosphor#40]
Phosphor modifies the vanilla chunk class, meaning cc can't add it's own patches.
Would it be possible for you and the developer of Cubic Chunks to find a way to work through this issue?

**Comment by jellysquid3** [comment]
Phosphor relies on many details of Minecraft's chunk system to implement certain optimizations, many of which Cubic Chunks changes. As such, adding support for the mod would require completely new research into specific optimizations for Cubic Chunk's system, likely necessitating a new mod all together.  

Unfortunately you will have to choose between which mod you have installed, but if you're looking for improving your game's performance, Phosphor looks like the superior tool.
