### ISSUE TITLE
Minecraft crash 1.12.2 Aether

### ISSUE THREAD

**Issue by Moconnor1852** [jellysquid3/Phosphor#41]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 8/18/19 9:58 PM
Description: Exception in server tick loop

java.lang.ClassCastException: com.gildedgames.orbis.lib.world.WorldObjectManager cannot be cast to com.gildedgames.orbis_api.world.WorldObjectManager
	at com.gildedgames.orbis_api.world.WorldObjectManager.get(WorldObjectManager.java:80)
	at com.gildedgames.orbis_api.world.WorldObjectManagerEvents.onWorldTick(WorldObjectManagerEvents.java:18)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_203_WorldObjectManagerEvents_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 467490568 bytes (445 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version       | Source                             | Signature                                |
	|:------ |:----------------- |:------------- |:---------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2        | minecraft.jar                      | None                                     |
	| LCHIJA | mcp               | 9.42          | minecraft.jar                      | None                                     |
	| LCHIJA | FML               | 8.0.99.99     | forge-1.12.2-14.23.5.2838.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2838  | forge-1.12.2-14.23.5.2838.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | orbis-lib         | 0.2.0         | orbis-lib-1.12.2-0.2.0+build74.jar | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | aether            | 0.2.1         | Aether-2-Mod-1.12.2.jar            | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | aether_legacy     | 1.4.4         | Aether-Legacy-Mod-1.12.2.jar       | None                                     |
	| LCHIJA | lost_aether       | 0.0.3         | Aether-Lost-Content-Mod-1.12.2.jar | None                                     |
	| LCHIJA | artemislib        | 1.0.6         | ArtemisLib-1.12.2-v1.0.6.jar       | None                                     |
	| LCHIJA | autoreglib        | 1.3-32        | AutoRegLib-1.3-32.jar              | None                                     |
	| LCHIJA | orbis_api         | 1.12.2-1.1.12 | Orbis-API-1.12.2.jar               | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | phosphor-lighting | 1.12.2-0.2.4  | phosphor-1.12.2-0.2.4+build46.jar  | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by jellysquid3** [comment]
This is not an issue with Phosphor. You have installed the Aether incorrectly.
