### ISSUE TITLE
Incompatibility with EigenCraft Unofficial Patch

### ISSUE THREAD

**Issue by NightMean** [jellysquid3/Phosphor#43]
The mod isn't on curseforge but it's on github
https://github.com/mrgrim/MUP
This mod apparently fixes desync issue with high efficiency tools (MC-5694) which we experience a lot on our server. Everytime it starts it throws this error
[crash-2019-09-16_19.26.36-client.txt](https://github.com/jellysquid3/Phosphor/files/3617431/crash-2019-09-16_19.26.36-client.txt)

**Comment by jellysquid3** [comment]
The other mod here appears to include their own set of patches to the lighting engine under the name "newlight". Unfortunately, their own patches are made redundant by the improved implementations in Phosphor and as such there is nothing that can be done to fix the issue short of disabling them on their side.

I would advise opening an issue on their tracker if you cannot manually disable these patches in the configuration file for the mod.
