### ISSUE TITLE
Game crashing 

### ISSUE THREAD

**Issue by Sroberts545** [jellysquid3/Phosphor#47]
i don't know what to do. I downloaded Phospher and put it in my mods folder and then when it started to crash the game i tried to delete it. When i start Minecraft up it re-downloads Phosphor. i found a way around it for a little bit, but now i can't play at all. The crash report said there were other conflicting mods so i moved those mods out of the mod folder and now it only says that Phospher is causing the crash. I don't know how to do all the coding stuff so if you can please help because i would like to play Minecraft again. 

Crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 10/13/19 12:25 PM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:870)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:269)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at net.minecraft.world.chunk.Chunk.func_76623_d(Chunk.java:870)
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:269)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207)

-- Affected level --
Details:
	Level name: New World now
	All players: 1 total; [EntityPlayerMP['HoboFriend'/279, l='New World now', x=-220.59, y=70.00, z=501.93]]
	Chunk stats: ServerChunkCache: 441 Drop: 16
	Level seed: -4172430083250978740
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-486,64,352), Chunk: (at 10,4,0 in -31,22; contains blocks -496,0,352 to -481,255,367), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 89202 game time, 102649 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 85129 (now: false), thunder time: 67841 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 587554984 bytes (560 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2835 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                           | Signature                                |
	|:------ |:-------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2835.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2835      | forge-1.12.2-14.23.5.2835.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | adventurepack        | 1.6.0             | Adventure-Tools-Mod-1.12.2.jar                   | None                                     |
	| LCHIJA | aether_legacy        | 1.4.4             | Aether-Legacy-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | lost_aether          | 0.0.3             | Aether-Lost-Content-Mod-1.12.2.jar               | None                                     |
	| LCHIJA | orbis-lib            | 0.2.0             | orbis-lib-1.12.2-0.2.0+build42.jar               | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | aether               | 0.2.0             | aether_ii-1.12.2-0.2.0+build42-universal.jar     | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | architecturecraft    | @VERSION@         | ArchitectureCraft-Mod-1.12.2.jar                 | None                                     |
	| LCHIJA | jei                  | 4.15.0.291        | jei_1.12.2-4.15.0.291 (1).jar                    | None                                     |
	| LCHIJA | athenaeum            | 1.12.2-1.17.3     | Athenaeum-Library-1.12.2.jar                     | None                                     |
	| LCHIJA | baubles              | 1.5.2             | Baubles-1.12-1.5.2 (1).jar                       | None                                     |
	| LCHIJA | atum                 | 2.0.4             | Atum-1.12.2-2.0.4 (1).jar                        | None                                     |
	| LCHIJA | autoreglib           | 1.3-15            | AutoRegLib-1.12.jar                              | None                                     |
	| LCHIJA | biomesoplenty        | 7.0.1.2297        | BiomesOPlenty-1.12.2-7.0.1.2297-universal.jar    | None                                     |
	| LCHIJA | cdm                  | 0.4.1             | cdm-0.4.1-mc1.12.2.jar                           | None                                     |
	| LCHIJA | cfm                  | 6.2.0             | cfm-6.2.0-mc1.12.2.jar                           | None                                     |
	| LCHIJA | codechickenlib       | 3.2.2.353         | CodeChickenLib-1.12.2 (2).jar                    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cookingforblockheads | 6.4.71            | Cooking-for-Blockheads-Mod-1.12.2.jar            | None                                     |
	| LCHIJA | tombstone            | 3.5.5             | Corail-Tombstone-Mod-1.12.2.jar                  | None                                     |
	| LCHIJA | extendedrenderer     | v1.0              | CoroUtil-1.12.2.jar                              | None                                     |
	| LCHIJA | coroutil             | 1.12.1-1.2.19     | CoroUtil-1.12.2.jar                              | None                                     |
	| LCHIJA | configmod            | v1.0              | CoroUtil-1.12.2.jar                              | None                                     |
	| LCHIJA | craftable_saddle     | 1.0.0             | Craftable Saddle.jar                             | None                                     |
	| LCHIJA | mocreatures          | 12.0.3            | DrZharks MoCreatures Mod-12.0.3.jar              | None                                     |
	| LCHIJA | golems               | 7.1.5             | Extra-Golems-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | farmingforblockheads | 3.1.28            | Farming-for-Blockheads-Mod-1.12.2.jar            | None                                     |
	| LCHIJA | floocraftft          | 1.9.6             | Floocraft-Mod-1.12.2.jar                         | None                                     |
	| LCHIJA | horsetweaks          | 1.0.5             | Horse-Tweaks-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | ism                  | 2.6.1 MC-1.12.2   | ism-2.6.1 MC-1.12.2.jar                          | None                                     |
	| LCHIJA | jeresources          | 0.9.2.60          | JustEnoughResources-1.12.2-0.9.2.60.jar          | None                                     |
	| LCHIJA | mantle               | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| LCHIJA | radixcore            | 1.12.x-2.2.1      | RadixCore-1.12.2.jar                             | None                                     |
	| LCHIJA | mca                  | 1.12.2-5.3.1      | MCA-1.12.x-5.3.1-universal.jar                   | None                                     |
	| LCHIJA | neat                 | 1.4-17            | Neat+1.4-17.jar                                  | None                                     |
	| LCHIJA | ore_dimension        | 1.0.0             | OreDimension.jar                                 | None                                     |
	| LCHIJA | harvestcraft         | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zf.jar                  | None                                     |
	| LCHIJA | additionalstructures | 2.3.0             | Rex's-Additional-Structures-1.12.x-(v.2.3.0).jar | None                                     |
	| LCHIJA | tconstruct           | 1.12.2-2.12.0.157 | TConstruct-1.12.2-2.12.0.157.jar                 | None                                     |
	| LCHIJA | terracore            | 2.1.0             | TerraCore-1.12.2.jar                             | None                                     |
	| LCHIJA | idk                  | 1.0.0             | Village-and-Pillage-Mod-1.12.2.jar               | None                                     |
	| LCHIJA | villagermarket       | 1.0.1             | Villager-Market-Mod-1.12.2.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | wearablebackpacks    | 3.1.0             | Wearable-Backpacks-Mod-1.12.2.jar                | None                                     |
	| LCHIJA | weather2             | 1.12.1-2.6.12     | Weather-Storms-Tornadoes-Mod-1.12.2 (1).jar      | None                                     |
	| LCHIJA | xaeroworldmap        | 1.4.10.1          | XaerosWorldMap_1.4.10.1_Forge_1.12.jar           | None                                     |
	| LCHIJA | xlfoodmod            | 1.12.2-1.3.0      | XL-Food-Mod-1.12.2.jar                           | None                                     |
	| LCHIJA | phosphor-lighting    | 1.12.2-0.2.6      | phosphor-1.12.2-0.2.6+build50-universal.jar      | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA | candymod             | 1.1.4             | Candy-World-Mod-1.12.2.jar                       | None                                     |

	Loaded coremods (and transformers): 
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)

**Comment by jellysquid3** [comment]
This is not an issue with Phosphor. The version of Forge your game has installed is known to be affected by this world-bricking bug. Please use Forge 14.23.5.2836 or newer to resolve the issue.
