### ISSUE TITLE
Incompadibility with LiteLoader 1.12.2

### ISSUE THREAD

**Issue by Thunderolf** [jellysquid3/Phosphor#48]
Mods: 
LiteLoader 1.12.2
forge1.12.2-14.23.5.2847
phosphor-1.12.2-0.2.6+build50-universal

[latest.log](https://github.com/jellysquid3/Phosphor/files/3733311/latest.log)

**Comment by jellysquid3** [comment]
LiteLoader provides an old version of Sponge Mixins, which causes compatibility issues with Phosphor and many other mods which depend on a newer version. It is not possible to resolve the issue on our side unless the authors of LiteLoader provide an update, which is unlikely given the last update has was two years ago.
