### ISSUE TITLE
[Client thread/WARN] [Phosphor]: Something (likely another mod) has attempted to modify the world's state from the wrong thread!

### ISSUE THREAD

**Issue by calloatti** [jellysquid3/Phosphor#5]
Seems like Atum 2 is doing something that Phosphor does not like:

https://paste.ee/p/tT3vI

Full log:

https://paste.ee/p/cdcsk

**Comment by jellysquid3** [comment]
This looks as if Atum is spawning particles with the server world through misuse of their proxy, similar to Biomes o' Plenty and Ice and Fire. I will take a look into investigating this once I'm available.

**Comment by jellysquid3** [comment]
My suspicion was correct. I've opened a pull request on the Atum 2 repository which fixes this issue. https://github.com/TeamMetallurgy/Atum2/pull/86

This issue will be closed as there's nothing more I can do to resolve the issue. Thank you for the report.
