### ISSUE TITLE
Error with class transformer (with OpenComputers mod)

### ISSUE THREAD

**Issue by tie** [jellysquid3/Phosphor#53]
Getting `java.lang.ClassCircularityError` exceptions in logs at startup.

#### Logs

- [debug.log](https://github.com/MightyPirates/OpenComputers/files/3913612/debug.log)
- [latest.log](https://github.com/MightyPirates/OpenComputers/files/3913613/latest.log)

#### Mods

- [Phosphor 0.2.6-50](https://curseforge.com/minecraft/mc-mods/phosphor/files/2747710)
- [OpenComputers 1.7.5.192](https://curseforge.com/minecraft/mc-mods/opencomputers/files/2828357)

SeeAlso: [MightyPirates/OpenComputers#3183](https://github.com/MightyPirates/OpenComputers/issues/3183)

**Comment by jellysquid3** [comment]
This doesn't appear to be an issue we can fix. Mixins is simply choking on code from the Scala standard library. You will need to use a mod such as [Forge Mixin Fix](https://www.curseforge.com/minecraft/mc-mods/forge-mixin-fix) to resolve the problem.
