### ISSUE TITLE
Shulker boxes lighting issue

### ISSUE THREAD

**Issue by Dissgruntled** [jellysquid3/Phosphor#57]
Phosphor 0.3.4 (Fabric)
[1.15.1] Fabric API 0.4.27 build 286

I am seeing a strange lighting issue that only seems to affect shulker boxes:

Without phosphor:
![2020-01-08_17 55 00](https://user-images.githubusercontent.com/19914628/72031443-49c2fd00-3241-11ea-8693-df675e578336.png)

With phosphor:
![2020-01-08_17 57 00](https://user-images.githubusercontent.com/19914628/72031464-56dfec00-3241-11ea-84ac-7f2509836eed.png)

The lighting issue is evident no matter where I am in the world, and also in every dimension.

**Comment by samolego** [comment]
I can confirm this, it has happened to me as well.

**Comment by jellysquid3** [comment]
Thanks for the report. The issue pertains to blocks with certain dynamic shapes (which seems to be limited to Shulker Boxes and Scaffolding in vanilla.) I've fixed the issue in Phosphor 0.3.5, which is already available for download on [Curseforge](https://www.curseforge.com/minecraft/mc-mods/phosphor).
