### ISSUE TITLE
java.lang.NullPointerException     at me.jellysquid.mods.phosphor.mod.PhosphorEvents.onPlayerJoinWorld

### ISSUE THREAD

**Issue by Chikko5** [jellysquid3/Phosphor#58]
Unexpected error

java.lang.NullPointerException
    at me.jellysquid.mods.phosphor.mod.PhosphorEvents.onPlayerJoinWorld(PhosphorEvents.java:26)

[latest.log](https://github.com/jellysquid3/Phosphor/files/4239329/latest.log)

[crash-2020-02-22_14.18.58-client.txt](https://github.com/jellysquid3/Phosphor/files/4239328/crash-2020-02-22_14.18.58-client.txt)

**Comment by jellysquid3** [comment]
Your mod JAR for Phosphor is corrupted, either from a bad download or filesystem corruption. The mixin config file is unable to be initialized earlier in the game's startup, which is what leads to this invalid state and subsequent crash.

```
java.lang.SecurityException: SHA-256 digest error for mixins.phosphor.json
```

Please make sure you are downloading from the [official CurseForge page.](https://www.curseforge.com/minecraft/mc-mods/phosphor).
