### ISSUE TITLE
Crash when run with Davinci's Vessels

### ISSUE THREAD

**Issue by FormMath** [jellysquid3/Phosphor#59]
As the title says, game crashes when run with MovingWorld and Davinci's Vessels installed.

Versions:
Minecraft: 1.12
Forge: 14.23.5.2847
Phosphor: 0.2.6
MovingWorld: 6.342
Davinci's Vessels: 6.340

Crash Report:
https://pastebin.com/1j9KbDX6

**Comment by jellysquid3** [comment]
`[17:55:53] [main/WARN] [mixin]: Mixin config mixins.phosphor.json requires mixin subsystem version 0.7.10 but 0.7.4 was found.`

`[17:55:50] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.4 Source=file:/Users/Test/Documents/Twitch/Instances/test/mods/movingworld-1.12-6.342-full.jar Service=LaunchWrapper Env=CLIENT`

Phosphor requires an up-to-date version of Mixins, but MovingWorld is providing an old version of Mixins which conflicts with our requirement. You need to update the mod or contact the author on having it updated.
