### ISSUE TITLE
[1.15.2-Forge]Server-Worker-4 died

### ISSUE THREAD

**Issue by EnterFor** [jellysquid3/Phosphor#63]
I don't know if this Mod caused it
It's about 6594 rows
[debug.log](https://github.com/jellysquid3/Phosphor/files/4332480/debug.log)

**Comment by EnterFor** [comment]
When I delete Phosphor, I can enter the game normally

**Comment by jellysquid3** [comment]
Fixed with 0.4.2-rc2.
